export const ADD_EVENT = 'ADD_EVENT';
export const SET_EVENTS = 'SET_EVENTS';
export const SET_ANNOUNCEMENTS = 'SET_ANNOUNCEMENTS';

export const REQUEST_EVENT = 'REQUEST_EVENT';
export const RECEIVE_EVENT = 'RECEIVE_EVENT';

export const START_MESSAGE_REQUEST = 'START_MESSAGE_REQUEST';
export const FINISH_MESSAGE_REQUEST = 'FINISH_MESSAGE_REQUEST';

export const REQUEST_ASSIGNED_USERS = 'REQUEST_ASSIGNED_USERS';
export const RECEIVED_ASSIGNED_USERS = 'RECEIVED_ASSIGNED_USERS';

export const SET_VIEW = 'SET_VIEW';

export const START_LOCATION_FETCH = 'START_LOCATION_FETCH';
export const FINISH_LOCATION_FETCH = 'FINISH_LOCATION_FETCH';
